# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
print(A.ndim, A.shape, A.size, A.dtype)


2 (3, 5) 15 int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2
D = B - C
E = B * C
F = B @ C
print(B)
print(C)
print(D)
print(E)
print(F)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [5]:
B = np.arange(1, 10).reshape(3, 3)
print(B)
print()
print(np.exp2(B))               # Exponentiating every element by 2
print()
print(np.min(B))                # Finds min value in matrix
print(np.min(B, axis=0))        # Finds min value in each column
print(np.min(B, axis=1))        # Finds min value in each row
print(np.argmin(B))             # Finds index for min value in matrix
print(np.argmin(B, axis=1))     # Finds index for min value in each row
print()
print(np.sum(B))                # Sums up all values in matrix
print(np.mean(B, axis=0))       # Finds the mean for each column
print(np.median(B, axis=0))     # Finds the median for each column

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[  2.   4.   8.]
 [ 16.  32.  64.]
 [128. 256. 512.]]

1
[1 2 3]
[1 4 7]
0
[0 0 0]

45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [6]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [7]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:** The missing indices are considered complete.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [8]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [10]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [11]:
a = np.arange(30)               # Creates an array of 30 numbers from 0 to 29.
b = a.reshape((2, 3, -1))       # Reshapes a into a 3D-matrix called b (2x3), -1 shapes the other dimensions automatically
print(a)                        # Prints the array (a)
print()
print(b)                        # Prints the matrix of (b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [12]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [13]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [14]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [15]:

def add_mult_matrices(matrix1, matrix2, operation):                             # Defines a function that takes 2 matrices then add or multiply depending on operation.
    
    if isinstance(matrix1, np.ndarray) and isinstance(matrix2, np.ndarray):     # Validates that arguments are True
        if operation == 'add':                                                  # Check if operation = add
            if matrix1.shape == matrix2.shape:                                  # Checks if matrices are the same sizes
                return matrix1 + matrix2                                        # Returns the sum of both matrices
            
        elif operation == 'multiply':                                           # Checks if operation = multiply, and if column of the first
            if matrix1.shape[1] == matrix2.shape[0]:                            
                return matrix1 @ matrix2
        
        else:
            print('Operation needs to be either add or multiply')               
    
    else:
        print('Arguments needs to be in np.ndarray')
            
        
matrix1 = np.array([[2, 3], [2,3]])
matrix2 = np.array([[2, 3], [2,3]])

print(add_mult_matrices(matrix1, matrix2, 'add'))
print()
print(add_mult_matrices(matrix1, matrix2, 'multiply'))
    

[[4 6]
 [4 6]]

[[10 15]
 [10 15]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

# 10.1.1

In [16]:
x = np.array([[4, 3]])

# a) Vilken dimension har vektorn x?
print(f'a:',x.shape)
# b) Beräkna 5x
print(f'b:', x * 5)
# c) Beräkna 3x
print(f'c:', x * 3)
# d) Beräkna 5x + 3x
print(f'd:', 5 * x + 3 * x)
# e) Beräkna 8x
print(f'e:', x * 8)
# f) Beräkna 4x - x
print(f'f:', 4 * x - x)
# g) Beräkna x-transponerat, vilken blir den nya dimensionen efter att transponeringen utförsts?
x.transpose
print(f'g:',x.shape)
# h) Är x + x.T definerat?
print("h: It's not defined because they dont have the same dimensions.")
# i) Beräkna ||x||
print(f'i:',np.linalg.norm(x))


a: (1, 2)
b: [[20 15]]
c: [[12  9]]
d: [[32 24]]
e: [[32 24]]
f: [[12  9]]
g: (1, 2)
h: It's not defined because they dont have the same dimensions.
i: 5.0


# 10.1.2

In [17]:
# Definera vektorn v enligt v-transponerat (3,7,0,11)
v = np.array([[3,7,0,11]])
v = v.T
# a) Vilken dimension har vektorn v?
print(f'a:',v.shape,'\n')
# b) Beräkna 2v
print(f'b:\n',v * 2,'\n')
# c) Beräkna 5v + 2v
print(f'c:\n',v * 5 + v * 2,'\n')
# d) Beräkna 4v - 2v
print(f'd:\n',v * 4 - v * 2,'\n')
# e) Beräkna v.T, vilken blir den nya dimensionen efter att transponeringen utförsts?
v = v.T
print(f'e:',v.shape,'\n')
# f) Beräkna ||v||
print(f'f:', np.linalg.norm(v),'\n')





a: (4, 1) 

b:
 [[ 6]
 [14]
 [ 0]
 [22]] 

c:
 [[21]
 [49]
 [ 0]
 [77]] 

d:
 [[ 6]
 [14]
 [ 0]
 [22]] 

e: (1, 4) 

f: 13.379088160259652 



# 10.1.3

In [18]:
# Definera vektorerna v1 = (4,3,1,5) och v2 = (2,3,1,1)
v1 = np.array([[4,3,1,5]])
v2 = np.array([[2,3,1,1]])

# a) Beräkna ||v1||
print(f'a:',np.linalg.norm(v1))
# b) Beräkna ||v1 - v2||
print(f'b:',np.linalg.norm(v1) - np.linalg.norm(v2))

a: 7.14142842854285
b: 3.2684450823354334


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

# 10.2.1

In [19]:
# Definera matriserna
a = np.array([[2,1,1],
             [1,-1,1]])

b = np.array([[4,-2,1],
             [2,-4,-2]])

c = np.array([[1,2],
             [2,1]])

d = np.array([[3,4],
             [4,3]])

e = np.array([[1],
             [2]])

i = np.array([[1,0],
             [0,1]])

# Om det är definerat, utför följande beräkningar:

# a) 2a
print(f'a:\n', a * 2,'\n')
# b) b - 2a
print(f'b:\n', b - a * 2,'\n')
# c) 3c - 2e
print(f'c: Not defined.\n')
# d) 2d - 3c
print(f'd:\n', 2 * d - 3 * c,'\n')
# e) d.T + 2d
print(f'e:\n', d.T + 2 * d,'\n')
# f) 2c.T - 2d.T
print(f'f:\n', 2 * c.T - 2 * d.T,'\n')
# g) a.T - b
print(f'g: Not defined.\n')
# h) ac
print(f'h: Not defined.\n')
# i) cd
print(f'i:\n', c @ d,'\n')
# j) cb
print(f'j:\n', c @ b,'\n')
# k) ci
print(f'k:\n', c @ i,'\n')
# l) ab.T
print(f'l:\n', a @ b.T)

a:
 [[ 4  2  2]
 [ 2 -2  2]] 

b:
 [[ 0 -4 -1]
 [ 0 -2 -4]] 

c: Not defined.

d:
 [[3 2]
 [2 3]] 

e:
 [[ 9 12]
 [12  9]] 

f:
 [[-4 -4]
 [-4 -4]] 

g: Not defined.

h: Not defined.

i:
 [[11 10]
 [10 11]] 

j:
 [[  8 -10  -3]
 [ 10  -8   0]] 

k:
 [[1 2]
 [2 1]] 

l:
 [[ 7 -2]
 [ 7  4]]


# 10.2.2

In [20]:
# Definera matrisen A = [2 3 4]
#                       [5 4 1]

A = np.array([[2,3,4],
              [5,4,1]])

# Beräkna A * A.T
print(A @ A.T)

[[29 26]
 [26 42]]


# 10.2.3

In [21]:
# Definera matriserna A = [1 2] B = [2 1] C = [4 3]
#                         [2 4]     [1 3]     [0 2]

A = np.array([[1,2],
              [2,4]])

B = np.array([[2,1],
              [1,3]])

C = np.array([[4,3],
              [0,2]])

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [22]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [23]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [24]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
